"""add category table and is_service to inventory_item

Revision ID: 0b33dda190e6
Revises: 926f958b1a15
Create Date: 2026-07-15 18:46:38.569117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b33dda190e6'
down_revision = '926f958b1a15'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create categories table only if it doesn't exist yet
    if 'categories' not in existing_tables:
        op.create_table('categories',
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=1024), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'name', name='uq_company_category_name')
        )
        existing_cat_indexes = [i['name'] for i in inspector.get_indexes('categories')]
        if 'ix_categories_company_id' not in existing_cat_indexes:
            with op.batch_alter_table('categories', schema=None) as batch_op:
                batch_op.create_index(batch_op.f('ix_categories_company_id'), ['company_id'], unique=False)

    # Add columns to inventory_items only if missing
    inv_cols = [c['name'] for c in inspector.get_columns('inventory_items')]
    cols_to_add = []
    if 'category_id' not in inv_cols:
        cols_to_add.append(sa.Column('category_id', sa.Integer(), nullable=True))
    if 'is_service' not in inv_cols:
        cols_to_add.append(sa.Column('is_service', sa.Boolean(), nullable=False, server_default='0'))

    if cols_to_add:
        with op.batch_alter_table('inventory_items', schema=None) as batch_op:
            for col in cols_to_add:
                batch_op.add_column(col)
            inv_indexes = [i['name'] for i in inspector.get_indexes('inventory_items')]
            if 'ix_inventory_items_category_id' not in inv_indexes and 'category_id' not in inv_cols:
                batch_op.create_index(batch_op.f('ix_inventory_items_category_id'), ['category_id'], unique=False)
            batch_op.create_foreign_key('fk_inventory_items_category_id', 'categories', ['category_id'], ['id'])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_items_category_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_items_category_id'))
        batch_op.drop_column('is_service')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_company_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
