"""Auto migration

Revision ID: 0c8a80a1e4fb
Revises: 6a160cf40b05
Create Date: 2026-06-01 07:57:32.916051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8a80a1e4fb'
down_revision = '6a160cf40b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_terms_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=1024), nullable=True))

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.alter_column('html_template_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.alter_column('html_template_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('payment_terms_days')
        batch_op.drop_column('legal_name')

    # ### end Alembic commands ###
