"""Add standard schedule fields to Employee

Revision ID: 21f4dcb595f6
Revises: c6d168cff81e
Create Date: 2026-06-03 17:40:07.848889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f4dcb595f6'
down_revision = 'c6d168cff81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('standard_end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('working_days', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('working_days')
        batch_op.drop_column('standard_end_time')
        batch_op.drop_column('standard_start_time')

    # ### end Alembic commands ###
