"""Add slug to Company

Revision ID: 50c607698792
Revises: ddacfaf54248
Create Date: 2026-06-07 21:43:12.486778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c607698792'
down_revision = 'ddacfaf54248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=64), nullable=True))

    # Backfill slugs
    import re
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, name FROM companies WHERE slug IS NULL")).fetchall()
    
    def build_slug(name):
        suffixes = ['llc', 'sa de cv', 's a de c v', 's.a.', 'inc', 'ltd', 'de c.v.', 'corp', 's.r.l.', 's. de r.l.', 'srl']
        clean_name = re.sub(r'[^a-z0-9]', ' ', name.lower())
        words = [w for w in clean_name.split() if w not in suffixes]
        slug = "".join(words)
        slug = re.sub(r'[^a-z0-9]', '', slug)[:30]
        return slug or "company"
        
    for row in rows:
        base_slug = build_slug(row[1])
        candidate = base_slug
        counter = 1
        while True:
            exists = conn.execute(sa.text("SELECT 1 FROM companies WHERE slug = :slug"), {"slug": candidate}).scalar()
            if not exists:
                break
            candidate = f"{base_slug}{counter}"
            counter += 1
            
        conn.execute(sa.text("UPDATE companies SET slug = :slug WHERE id = :id"), {"slug": candidate, "id": row[0]})

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
