"""add document templates

Revision ID: 6a160cf40b05
Revises: be74a037a830
Create Date: 2026-05-31 00:24:46.216698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a160cf40b05'
down_revision = 'be74a037a830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('pdf_overlay', 'html', name='documenttemplatetype'), nullable=False),
    sa.Column('pdf_background_path', sa.String(length=255), nullable=True),
    sa.Column('pdf_coordinates', sa.JSON(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_company_id'))

    op.drop_table('document_templates')
    # ### end Alembic commands ###
