"""add project_id to document

Revision ID: 6af85a17e660
Revises: 50c607698792
Create Date: 2026-06-08 19:25:46.814722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af85a17e660'
down_revision = '50c607698792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_documents_project_id', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
