"""Auto migration

Revision ID: 749cb1581826
Revises: 8698fd4ab822
Create Date: 2026-06-05 19:04:58.050539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749cb1581826'
down_revision = '8698fd4ab822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.create_foreign_key('fk_expenses_transaction_id', 'transactions', ['transaction_id'], ['id'])

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ledger_entries_transaction_id', 'transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ledger_entries_transaction_id', type_='foreignkey')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_transaction_id', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'draft'"))

    # ### end Alembic commands ###
