"""accounting: add Transaction model, Account.code, Expense.status/vendor/category, remove Account.balance

Revision ID: 8698fd4ab822
Revises: 21f4dcb595f6
Create Date: 2026-06-03 20:18:12.169205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8698fd4ab822'
down_revision = '21f4dcb595f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.String(length=512), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('transaction_type', sa.Enum('journal', 'expense', 'income', 'payment', 'transfer', name='transactiontype'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_voided'), ['is_voided'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.create_index(batch_op.f('ix_accounts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_active'), ['is_active'], unique=False)
        batch_op.drop_column('balance')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'approved', 'paid', name='expensestatus'), nullable=True, server_default='draft'))
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ledger_entries_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_reference_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_reference_id'))
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_column('status')
        batch_op.drop_column('category')
        batch_op.drop_column('vendor_name')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.drop_index(batch_op.f('ix_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_accounts_code'))
        batch_op.drop_column('is_active')
        batch_op.drop_column('code')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_voided'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_by'))
        batch_op.drop_index(batch_op.f('ix_transactions_company_id'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
