"""add accounting_attachments table

Revision ID: 89ddd12bc651
Revises: e1a2b3c4d5f6
Create Date: 2026-06-17 22:01:38.903910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ddd12bc651'
down_revision = 'e1a2b3c4d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_attachments',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_attachments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_attachments_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_attachments_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_attachments_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_attachments_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_accounting_attachments_reference_type'))
        batch_op.drop_index(batch_op.f('ix_accounting_attachments_reference_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_attachments_company_id'))

    op.drop_table('accounting_attachments')
    # ### end Alembic commands ###
