"""Update models

Revision ID: 8abc28cd44ee
Revises: d1e2f3a4b5c6
Create Date: 2026-05-27 23:56:13.216140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abc28cd44ee'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('table_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('tax_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)
        batch_op.drop_index('ix_companies_identifier')
        batch_op.create_index(batch_op.f('ix_companies_identifier'), ['identifier'], unique=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # Helper: check if index exists before creating
    from sqlalchemy import inspect as sa_inspect
    conn = op.get_bind()
    insp = sa_inspect(conn)

    def _create_index_if_not_exists(table_name, index_name, columns, unique=False):
        existing = [i['name'] for i in insp.get_indexes(table_name)]
        if index_name not in existing:
            op.create_index(index_name, table_name, columns, unique=unique)

    with op.batch_alter_table('document_items', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)

    _create_index_if_not_exists('document_items', 'ix_document_items_document_id', ['document_id'])
    _create_index_if_not_exists('document_items', 'ix_document_items_inventory_item_id', ['inventory_item_id'])

    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sequences_cai'), ['cai'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sequences_expiration_date'), ['expiration_date'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_cache', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_cache', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('draft', 'sent', 'issued', 'partial', 'paid', 'overdue', 'pending', 'credit_note', 'exchange', 'cancelled', name='documentstatus'),
               existing_nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.create_unique_constraint('uq_document_per_company', ['company_id', 'document_number'])

    _create_index_if_not_exists('documents', 'ix_documents_client_id', ['client_id'])
    _create_index_if_not_exists('documents', 'ix_documents_company_id', ['company_id'])
    _create_index_if_not_exists('documents', 'ix_documents_document_number', ['document_number'])
    _create_index_if_not_exists('documents', 'ix_documents_due_date', ['due_date'])
    _create_index_if_not_exists('documents', 'ix_documents_issued_date', ['issued_date'])
    _create_index_if_not_exists('documents', 'ix_documents_user_id', ['user_id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)

    _create_index_if_not_exists('inventory_items', 'ix_inventory_items_company_id', ['company_id'])
    _create_index_if_not_exists('inventory_items', 'ix_inventory_items_name', ['name'])
    _create_index_if_not_exists('inventory_items', 'ix_inventory_items_supplier_id', ['supplier_id'])

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('credit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_date'), ['date'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('payment_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    _create_index_if_not_exists('payments', 'ix_payments_company_id', ['company_id'])
    _create_index_if_not_exists('payments', 'ix_payments_document_id', ['document_id'])
    _create_index_if_not_exists('payments', 'ix_payments_payment_date', ['payment_date'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    _create_index_if_not_exists('purchase_order_items', 'ix_purchase_order_items_inventory_item_id', ['inventory_item_id'])
    _create_index_if_not_exists('purchase_order_items', 'ix_purchase_order_items_item_code', ['item_code'])
    _create_index_if_not_exists('purchase_order_items', 'ix_purchase_order_items_purchase_order_id', ['purchase_order_id'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_purchase_order_per_company', ['company_id', 'order_number'])

    _create_index_if_not_exists('purchase_orders', 'ix_purchase_orders_buy_date', ['buy_date'])
    _create_index_if_not_exists('purchase_orders', 'ix_purchase_orders_company_id', ['company_id'])
    _create_index_if_not_exists('purchase_orders', 'ix_purchase_orders_order_number', ['order_number'])
    _create_index_if_not_exists('purchase_orders', 'ix_purchase_orders_supplier_id', ['supplier_id'])

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)

    _create_index_if_not_exists('stock_movements', 'ix_stock_movements_company_id', ['company_id'])
    _create_index_if_not_exists('stock_movements', 'ix_stock_movements_date', ['date'])
    _create_index_if_not_exists('stock_movements', 'ix_stock_movements_inventory_item_id', ['inventory_item_id'])
    _create_index_if_not_exists('stock_movements', 'ix_stock_movements_reference', ['reference'])
    _create_index_if_not_exists('stock_movements', 'ix_stock_movements_user_id', ['user_id'])

    # Handle users table - check if 'active' column still exists
    user_cols = [c['name'] for c in insp.get_columns('users')]
    if 'active' in user_cols and 'status' not in user_cols:
        with op.batch_alter_table('users', schema=None) as batch_op:
            # 1. Add status as nullable temporarily
            batch_op.add_column(sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='userstatus'), nullable=True))
            
        # 2. Migrate data
        op.execute("UPDATE users SET status = 'active' WHERE active = 1")
        op.execute("UPDATE users SET status = 'inactive' WHERE active = 0")
        
        with op.batch_alter_table('users', schema=None) as batch_op:
            # 3. Make status non-nullable and drop active
            batch_op.alter_column('status', nullable=False)
            batch_op.drop_column('active')
    elif 'status' not in user_cols:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='userstatus'), nullable=False,
                                          server_default='active'))

    # Also add last_login if it doesn't exist
    user_cols_now = [c['name'] for c in insp.get_columns('users')]
    if 'last_login' not in user_cols_now:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))
        
    op.execute("UPDATE users SET active = 1 WHERE status = 'active'")
    op.execute("UPDATE users SET active = 0 WHERE status = 'inactive'")
    op.execute("UPDATE users SET active = 0 WHERE status = 'suspended'")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_reference'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_date'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_company_id'))
        batch_op.alter_column('notes',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_purchase_order_per_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_company_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_buy_date'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_inventory_item_id'))
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.alter_column('budget',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_document_id'))
        batch_op.drop_index(batch_op.f('ix_payments_company_id'))
        batch_op.alter_column('payment_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_date'))
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_company_id'))
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cost_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_date'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_per_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_issued_date'))
        batch_op.drop_index(batch_op.f('ix_documents_due_date'))
        batch_op.drop_index(batch_op.f('ix_documents_document_number'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))
        batch_op.drop_index(batch_op.f('ix_documents_client_id'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'sent', 'issued', 'partial', 'paid', 'overdue', 'pending', 'credit_note', 'exchange', 'cancelled', name='documentstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('tax_cache')
        batch_op.drop_column('subtotal_cache')

    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sequences_expiration_date'))
        batch_op.drop_index(batch_op.f('ix_document_sequences_cai'))

    with op.batch_alter_table('document_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_items_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_document_items_document_id'))
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_identifier'))
        batch_op.create_index('ix_companies_identifier', ['identifier'], unique=False)
        batch_op.alter_column('tax_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('table_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_default'))
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
