"""auto migration

Revision ID: 926f958b1a15
Revises: f6a7b8c9d0e1
Create Date: 2026-07-04 23:49:23.618011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926f958b1a15'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_payments_pos_register_session_id', 'pos_register_sessions', ['pos_register_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_pos_register_session_id', type_='foreignkey')

    # ### end Alembic commands ###
