"""Add warehouses

Revision ID: be74a037a830
Revises: f5d882475acb
Create Date: 2026-05-30 21:23:14.141483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be74a037a830'
down_revision = 'f5d882475acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_warehouse_name_per_company')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_company_id'), ['company_id'], unique=False)

    op.create_table('warehouse_items',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='check_warehouse_quantity_non_negative'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'inventory_item_id', name='uq_warehouse_inventory_item')
    )
    with op.batch_alter_table('warehouse_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_items_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_items_warehouse_id'), ['warehouse_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key('fk_documents_warehouse_id', 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_orders_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key('fk_purchase_orders_warehouse_id', 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('destination_warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_movements_destination_warehouse_id'), ['destination_warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_foreign_key('fk_stock_movements_destination_warehouse_id', 'warehouses', ['destination_warehouse_id'], ['id'])
        batch_op.create_foreign_key('fk_stock_movements_warehouse_id', 'warehouses', ['warehouse_id'], ['id'])

    # Data Migration
    op.execute("""
        INSERT INTO warehouses (company_id, name, location, is_active, is_deleted, created_at, updated_at)
        SELECT id, 'Sede Principal', 'Main Location', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM companies
    """)

    op.execute("""
        INSERT INTO warehouse_items (warehouse_id, inventory_item_id, quantity, is_deleted, created_at, updated_at)
        SELECT w.id, i.id, i.quantity, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM inventory_items i
        JOIN warehouses w ON w.company_id = i.company_id AND w.name = 'Sede Principal'
    """)

    op.execute("""
        UPDATE stock_movements
        SET warehouse_id = (
            SELECT id FROM warehouses 
            WHERE warehouses.company_id = stock_movements.company_id 
            AND warehouses.name = 'Sede Principal'
        )
    """)

    op.execute("""
        UPDATE documents
        SET warehouse_id = (
            SELECT id FROM warehouses 
            WHERE warehouses.company_id = documents.company_id 
            AND warehouses.name = 'Sede Principal'
        )
    """)

    op.execute("""
        UPDATE purchase_orders
        SET warehouse_id = (
            SELECT id FROM warehouses 
            WHERE warehouses.company_id = purchase_orders.company_id 
            AND warehouses.name = 'Sede Principal'
        )
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stock_movements_warehouse_id', type_='foreignkey')
        batch_op.drop_constraint('fk_stock_movements_destination_warehouse_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_destination_warehouse_id'))
        batch_op.drop_column('destination_warehouse_id')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_orders_warehouse_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_warehouse_id'))
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_warehouse_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_warehouse_id'))
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('warehouse_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_items_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_items_inventory_item_id'))

    op.drop_table('warehouse_items')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_company_id'))

    op.drop_table('warehouses')
    # ### end Alembic commands ###
