"""Increase PO item price and total to 5 decimal places

Revision ID: c5fdf769a3df
Revises: e635f316840c
Create Date: 2026-06-07 15:45:03.034548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fdf769a3df'
down_revision = 'e635f316840c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=5),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=5),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=5),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###
