"""Add SKU to inventory items

Revision ID: ddacfaf54248
Revises: d562d6c20513
Create Date: 2026-06-07 21:09:38.042300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddacfaf54248'
down_revision = 'd562d6c20513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_items_sku'), ['sku'], unique=False)

    # Backfill SKU for existing rows: ITEM-NAME-SLUG-{id}
    import re
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, name FROM inventory_items WHERE sku IS NULL")).fetchall()
    for row in rows:
        slug = re.sub(r'[^A-Z0-9]+', '-', row[1].upper().strip()).strip('-')[:24]
        sku = f"{slug}-{row[0]}"
        conn.execute(sa.text("UPDATE inventory_items SET sku = :sku WHERE id = :id"), {"sku": sku, "id": row[0]})

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_company_sku', ['company_id', 'sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_company_sku', type_='unique')
        batch_op.drop_index(batch_op.f('ix_inventory_items_sku'))
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
