"""update last_login nullable

Revision ID: e24269f70ee6
Revises: 8abc28cd44ee
Create Date: 2026-05-28 00:29:49.715317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24269f70ee6'
down_revision = '8abc28cd44ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_document_number')
        batch_op.create_index(batch_op.f('ix_documents_document_number'), ['document_number'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_orders_order_number')
        batch_op.create_index(batch_op.f('ix_purchase_orders_order_number'), ['order_number'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_order_number'))
        batch_op.create_index('ix_purchase_orders_order_number', ['order_number'], unique=1)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_document_number'))
        batch_op.create_index('ix_documents_document_number', ['document_number'], unique=1)

    # ### end Alembic commands ###
