"""add tags

Revision ID: f5d882475acb
Revises: e24269f70ee6
Create Date: 2026-05-28 21:34:41.149528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d882475acb'
down_revision = 'e24269f70ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_company_tag_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_company_id'), ['company_id'], unique=False)

    op.create_table('expense_tags',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id', 'tag_id')
    )
    with op.batch_alter_table('expense_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_tags_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('ledger_entry_tags',
    sa.Column('ledger_entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_entry_id', 'tag_id')
    )
    with op.batch_alter_table('ledger_entry_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entry_tags_ledger_entry_id'), ['ledger_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entry_tags_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entry_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entry_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entry_tags_ledger_entry_id'))

    op.drop_table('ledger_entry_tags')
    with op.batch_alter_table('expense_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_expense_tags_expense_id'))

    op.drop_table('expense_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_company_id'))

    op.drop_table('tags')
    # ### end Alembic commands ###
